### ISSUE TITLE
Custom captcha support

### ISSUE THREAD

**Issue by developervariety** [Zaczero/AntiCaptcha#4]

**Comment by Zaczero** [comment]
Hi, not sure what exactly you have in mind by 'custom captcha' but this library already supports image captchas and an example can be found in the README file.

**Comment by developervariety** [comment]
Hey @Zaczero,

https://github.com/AdminAnticaptcha/anticaptcha-csharp/blob/master/Api/CustomCaptcha.cs - custom captcha can be found here.
