### ISSUE TITLE
TaskId overflows int

### ISSUE THREAD

**Issue by FlashPlayer13** [Zaczero/AntiCaptcha#5]
TaskId on client side need to be changed to long type

**Comment by wmail-ak** [comment]
I also have this error
Newtonsoft.Json.JsonReaderException: 'JSON integer 2151574698 is too large or small for an Int32. Path 'taskId', line 1, position 32.'

**Comment by jovargas** [comment]
+1 here
I've made a pull request changing TaskId to long type.

**Comment by Zaczero** [comment]
Fixed in v1.4.2. Thank you all for reporting and @jovargas for a quick fix.

https://github.com/Zaczero/AntiCaptcha/releases/tag/v1.4.2

:)
